#Optional - The name of the workflow as it will appear in the "Actions" tab of the GitHub repository.
name: Serenity Cucumber Selenium Test Automation Run


#controls when the action will run
#and specifies the trigger for this workflow (which is workflow_dispatch).
on:
  #The "workflow_dispatch" event allows you to manually trigger a workflow run through the GitHub Actions UI
  workflow_dispatch


#Groups together all the jobs that run in the Serenity Cucumber Selenium Test Automation Run workflow.
jobs:
  #this workflow contains a single job called "build"
  build:
    #the type of runner that the job will run on
#    runs-on: ubuntu-latest
    runs-on: macos-latest
    #Groups together all the steps that run in the build job.
    steps:
      #Each item nested under this section is a separate action or shell script.
      - name: Step 1 - checkout main branch from GitHub
        uses: actions/checkout@v2
      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Step 3 - Build with Maven
        #The run keyword tells the job to execute a command on the runner
        run: mvn clean verify
      - name: Step 4 - Archive Serenity Index HTML
        uses: actions/upload-artifact@v2
        with:
          name: serenity-index
          path: target/site/serenity/index.html